---
title: "Mapping using R"
description: |
  Here is an example of my mapping skills using R for a class assignment.
author:
  - name: Madeleine Deisen
date: 04-18-2021
output:
  distill::distill_article:
    self_contained: false
categories:
  - data
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(readxl)
library(janitor)
library(glue)
library(leaflet)
library(RColorBrewer)
library(htmlwidgets)
library(htmltools)
library(tigris)
library(tmap)
library(tmaptools)
options(tigris_class = "sf")
```

I created a map of residential sales in Sacramento, California using Leaflet. The size of the dots corresponds to the price of each sale.

```{r}
sac_sales <- read_csv("https://support.spatialkey.com/wp-content/uploads/2021/02/Sacramentorealestatetransactions.csv")

sac_sales_residential <- sac_sales %>%
  filter(type == "Residential")
  
leaflet(sac_sales_residential) %>%
  addTiles() %>%
  addCircles(lng = ~longitude, lat = ~latitude, weight = 1, radius = ~sqrt(price))

```
